spring.application.name=observability-backend
# Server
server.port=8080

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=observability-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Logging
logging.level.com.telecom=DEBUG
logging.level.org.springframework.web.socket=DEBUG